from django.urls import path, include
from .frontendview import *
urlpatterns = [
    path('main/', main),
    path('', login),
    path('forgetpassword/', forgetpassword_view),
    # path('departments/', department_view),
    # path('phase/', phase_view),
    path('admindashboard/', admin_view),
    path('rawmaterial/', rawmaterial_view),
    path('billofmaterial', billof_material_view),
    path('product/', product_view),
    # path('branch', branch_view),
    # path('user-role/', user_role_view),
    # path('subdivision/', sub_division_view),
    # path('productionflow/', production_flow),
    path('productionflow/', productionflow),
    # path('user/', user_view),
    path('parties/', party_view),
    # path('partytype/', party_type_view),
    # path('country/', country_view),
    path('data-management/', common_view),
    path('inventory-maintenance', inventory_maintenance_view),
    path('purchase/', new_purchase_request),
    path('new-sales-order/', sales_order_create_view),
    path('sales-order/', sales_order_view),
    path('return/', return_goods_view),
    path('inventory', inventory_menu_view),
    path('production-order/', produciton_order_view),
    path('purchase-request/', purchase_request_view),
    path('newproduction/', new_produciton_view),
    path('manualdelivery-note', manual_deliverynote_view),
    path('inventory_type', inventory_transfer_view),
    path('inventorytransfer', inventory_transfer_view),
    path('return_goods/', return_goods_view),
    path('goods_recipt_note/', goods_recipts_note_view),
    path('purchase-inquiry', purchase_inquiry_view),
    path('purchase-order', purchase_order_view),
    path('fr', frondend_view)
]
